name                : Epic Bounties
# baseurl             : "/EpicWeb" # does not include hostname

# Where things are
source              : .
destination         : ./_site
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# For RSS
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-category-pages
  - jekyll/tagging
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  
feed:
  path: feed.xml

# Blog
collections:
  posts:
    title           : Posts
    output          : true
    permalink       : /blog/:title
    
category_path       : blog/categories
category_layout     : category.html

tag_feed_dir        : blog/tags
tag_page_dir        : blog/tags
tag_page_layout     : tag

# Languages
languages                   : ["es", "en"]
# exclude_from_localizations  : ["assets"]
default_locale_in_subfolder : true

# Outputting
paginate            : 5
paginate_path       : /blog/:num
timezone            : Europe/Madrid

quiet               : false
verbose             : false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
show_dir_listing    : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false